security:
    # https://symfony.com/doc/current/security/authenticator_manager.html
  enable_authenticator_manager: true
  password_hashers:
    App\Security\SecurityUser:
      algorithm: auto

  # https://symfony.com/doc/current/security.html#c-hashing-passwords
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    # used to reload user from session & other features (e.g. switch_user)
    user_provider:
      id: App\Security\UserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: user_provider
      # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

  role_hierarchy:
    ROLE_TRAINER: ROLE_CLIENT
    ROLE_ADMIN: ROLE_TRAINER

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    # Users
    - { path: ^/user/create, roles: ROLE_ADMIN }
    - { path: ^/update/user_data, roles: ROLE_ADMIN }
    - { path: ^/get/users_data, roles: ROLE_CLIENT }
    - { path: ^/users/remove, roles: ROLE_ADMIN }
    - { path: ^/user/trainers, roles: ROLE_CLIENT }

    # Training
    - { path: ^/create/training, roles: ROLE_ADMIN }
    - { path: ^/edit/training, roles: ROLE_ADMIN }
    - { path: ^/edit/training/trainer, roles: ROLE_ADMIN }
    - { path: ^/edit/training/time, roles: ROLE_ADMIN }
    - { path: ^/edit/training/status, roles: ROLE_ADMIN }
    - { path: ^/remove/base_training, roles: ROLE_ADMIN }
    - { path: ^/remove/training, roles: ROLE_ADMIN }
    - { path: ^/remove/courses, roles: ROLE_ADMIN }
    - { path: ^/remove/halls, roles: ROLE_ADMIN }
    - { path: ^/edit/course, roles: ROLE_ADMIN }
    - { path: ^/edit/hall, roles: ROLE_ADMIN }
    - { path: ^/list/trainings, roles: ROLE_CLIENT }
    - { path: ^/list/courses, roles: ROLE_CLIENT }
    - { path: ^/create/hall, roles: ROLE_ADMIN }
    - { path: ^/list/halls, roles: ROLE_CLIENT }
    - { path: ^/create/course, roles: ROLE_ADMIN }

    # Notification
    - { path: ^/notify, roles: ROLE_ADMIN }
