const SIDEBAR_WIDTH = 208
const HEADER_HEIGHT = 55
const MARGINS = 10
const USERS_TABLE_HEADER_HEIGHT = 55
const USERS_TABLE_FOOTER_HEIGHT = 64
const USERS_ACTION_BUTTONS_HEIGHT = 50

export {
    SIDEBAR_WIDTH,
    HEADER_HEIGHT,
    MARGINS,
    USERS_TABLE_HEADER_HEIGHT,
    USERS_TABLE_FOOTER_HEIGHT,
    USERS_ACTION_BUTTONS_HEIGHT,
}